server:
  port: 7777

invoicing-system:
 database: memory


logging:
  level:
    org:
      springframework:
        boot: INFO
    pl:
      future-collars:
        invoicing: INFO
        invoicing.db: DEBUG

