server:
  port: 7777

invoicing-system:
  database: file
  database.directory: db
  database.invoices.file: invoices.txt
  database.id.file: id.txt

logging:
  level:
    org:
      springframework:
        boot: INFO
    pl:
      future-collars:
        invoicing: INFO
        invoicing.db: DEBUG

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher